import React, { useState, useRef, useEffect } from 'react';
import { db } from '@/api/supabaseClient';
import { triggerWorkflows } from '@/lib/workflowExecutor';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card } from '@/components/ui/card';
import { Sparkles, Send, Loader2, ArrowRight, Gift, Mail } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import { toast } from 'sonner';
import { motion, AnimatePresence } from 'motion/react';
async function invokeLLM(prompt) {
  const response = await fetch('https://api.anthropic.com/v1/messages', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ model: 'claude-sonnet-4-20250514', max_tokens: 1000, messages: [{ role: 'user', content: prompt }] }) });
  const data = await response.json();
  return data.content?.map(b => b.text || '').join('') || '';
}
export default function QRLanding() {
  const [step, setStep] = useState('welcome');
  const [messages, setMessages] = useState([]);
  const [input, setInput] = useState('');
  const [loading, setLoading] = useState(false);
  const [email, setEmail] = useState('');
  const [name, setName] = useState('');
  const messagesEndRef = useRef(null);
  useEffect(() => { messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' }); }, [messages]);
  const startChat = async () => { setStep('chat'); setLoading(true); try { const result = await invokeLLM(`You are a friendly AI business helper at a craft market stall. Someone just scanned a QR code. Greet them warmly and ask 3 quick questions: 1. What kind of business or craft do they do? 2. What's their biggest challenge right now? 3. What would help them most today? Be warm, use emojis, keep it short.`); setMessages([{ role: 'assistant', content: result }]); } catch { toast.error('Something went wrong'); } finally { setLoading(false); } };
  const sendMessage = async () => { if (!input.trim()) return; const userMsg = input; setInput(''); const updated = [...messages, { role: 'user', content: userMsg }]; setMessages(updated); setLoading(true); const history = updated.map(m => `${m.role === 'user' ? 'Customer' : 'AI'}: ${m.content}`).join('\n\n'); try { const result = await invokeLLM(`You are a friendly AI business helper at a craft market stall.\nConversation:\n${history}\nGive a simple action plan, suggest ways to make more sales, be encouraging. Max 200 words, use emojis. If you've given good advice, suggest: "Would you like a free AI guide? I just need your email 📧"`); setMessages([...updated, { role: 'assistant', content: result }]); } catch { toast.error('Something went wrong'); } finally { setLoading(false); } };
  const submitEmail = async () => { if (!email) return toast.error('Please enter your email'); try { const lead = await db.entities.Lead.create({ name, email, source: 'qr_scan', status: 'new', notes: messages.map(m => `${m.role}: ${m.content}`).join('\n') }); await db.entities.ActionLog.create({ action: 'lead_captured', entity_type: 'lead', entity_id: lead.id, details: { summary: `New lead via QR: ${name || email}` } }); const context = { leadId: lead.id, leadEmail: email, leadName: name, source: 'qr_scan' }; triggerWorkflows('qr_scan', context).catch(() => {}); triggerWorkflows('new_lead', context).catch(() => {}); setStep('thankyou'); toast.success("You're in! 🎉"); } catch { toast.error('Something went wrong'); } };
  if (step === 'welcome') return (<div className="min-h-screen bg-gradient-to-b from-background to-secondary/30 flex items-center justify-center p-4"><motion.div initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }} className="max-w-md w-full text-center space-y-6"><div className="w-20 h-20 rounded-2xl bg-primary/10 flex items-center justify-center mx-auto"><Sparkles className="w-10 h-10 text-primary" /></div><div><h1 className="font-display text-3xl font-bold">Free AI Help</h1><h2 className="font-display text-xl text-primary mt-1">For Your Business</h2><p className="text-muted-foreground mt-3 text-sm">Get instant personalised advice to grow your business ✨</p></div><Button size="lg" onClick={startChat} className="gap-2 w-full"><ArrowRight className="w-5 h-5" /> Get My Free Advice</Button><p className="text-xs text-muted-foreground">No signup needed to start chatting</p></motion.div></div>);
  if (step === 'chat') return (<div className="min-h-screen bg-gradient-to-b from-background to-secondary/30 flex flex-col"><div className="flex-1 overflow-y-auto p-4 space-y-4 max-w-lg mx-auto w-full"><div className="pt-6 text-center"><div className="w-12 h-12 rounded-xl bg-primary/10 flex items-center justify-center mx-auto mb-2"><Sparkles className="w-6 h-6 text-primary" /></div><p className="text-xs text-muted-foreground">Heritage Craft Media AI</p></div><AnimatePresence>{messages.map((msg, i) => <motion.div key={i} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}><div className={`max-w-[85%] rounded-2xl px-4 py-3 text-sm ${msg.role === 'user' ? 'bg-primary text-primary-foreground' : 'bg-card border shadow-sm'}`}>{msg.role === 'assistant' ? <div className="prose prose-sm max-w-none"><ReactMarkdown>{msg.content}</ReactMarkdown></div> : msg.content}</div></motion.div>)}</AnimatePresence>{loading && <div className="flex justify-start"><div className="bg-card border rounded-2xl px-4 py-3"><Loader2 className="w-4 h-4 animate-spin text-muted-foreground" /></div></div>}<div ref={messagesEndRef} /></div>{messages.length >= 3 && <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="p-4 max-w-lg mx-auto w-full"><Card className="p-4 border-primary/20 bg-primary/5"><p className="font-medium text-sm mb-3 flex items-center gap-2"><Gift className="w-4 h-4 text-primary" /> Get your free personalised guide</p><div className="space-y-2"><Input placeholder="Your name (optional)" value={name} onChange={(e) => setName(e.target.value)} /><Input placeholder="Your email *" type="email" value={email} onChange={(e) => setEmail(e.target.value)} /><Button className="w-full gap-2" onClick={submitEmail}><Mail className="w-4 h-4" /> Send My Free Guide</Button></div><p className="text-xs text-muted-foreground mt-2">No spam. Unsubscribe anytime.</p></Card></motion.div>}<div className="p-4 border-t bg-background/80 backdrop-blur-sm max-w-lg mx-auto w-full"><div className="flex gap-2"><Input placeholder="Type your message..." value={input} onChange={(e) => setInput(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && !e.shiftKey && sendMessage()} /><Button size="icon" onClick={sendMessage} disabled={loading || !input.trim()}><Send className="w-4 h-4" /></Button></div></div></div>);
  if (step === 'thankyou') return (<div className="min-h-screen bg-gradient-to-b from-background to-secondary/30 flex items-center justify-center p-4"><motion.div initial={{ opacity: 0, scale: 0.9 }} animate={{ opacity: 1, scale: 1 }} className="max-w-md w-full text-center space-y-6"><div className="w-20 h-20 rounded-2xl bg-green-100 flex items-center justify-center mx-auto"><span className="text-4xl">🎉</span></div><div><h1 className="font-display text-3xl font-bold">You're In!</h1><p className="text-muted-foreground mt-3 text-sm">Check your inbox — your free guide is on its way.</p></div><p className="text-xs text-muted-foreground">You can close this page now ✨</p></motion.div></div>);
  return null;
}
